Tip calculator app main -- Add functionality
M-AminAlizadeh/Frontend-Mentor-projects pull request #9
Opened 2023-07-24 08:30 UTC by M-AminAlizadeh

The things that I did in this PR:

2023-07-25 20:12 UTC, ahangarha requested changes
Good job 👍🏾 

![](https://media.giphy.com/media/qJ2kyXafep2Z9j1IKI/giphy.gif)

Most of your work was great, but I have made some comments. Please take a look. There are two required changes and the others are optional.

Bests

2023-07-25 20:12 UTC, ahangarha commented on tip-calculator-app-main/scripts/modules/btnSelection.js
> +const btnSelection = () => {
# Optional

I recommend using better name for this function. What is it supposed to do? Maybe it `add even listener to select tip buttons`.

2023-07-25 20:12 UTC, ahangarha commented on tip-calculator-app-main/scripts/modules/errorHandler.js
# 🚫 Changes required

You have done an excellent job here, but there is one more case that is not handled: typing non-numeric characters!

This needs to be handled both on HTML and on JS side.

2023-07-25 20:12 UTC, ahangarha commented on tip-calculator-app-main/style/style.css
> +}
# Optional

Try to avoid using `!important`. Almost in all cases, using `!important` is a sign of not using the right CSS selectors. Check out specificity.

I don't make this a blocker, but it is really serious. As the first `!important` enters the styles, it brings its entire gang!

2023-07-26 08:29 UTC, M-AminAlizadeh commented on tip-calculator-app-main/scripts/index.js
> +errorHandler();
Absolutely right
I wrote them before building the functions and forgot to delete them
About the naming functions I changed it to `calculateAndDisplayData`  it's a verb and explains what exactly it does

2023-07-26 08:35 UTC, M-AminAlizadeh commented on .eslintrc.json
> +}
I copied the config scripts from Microverse eslint config
I will change it to error to show me an error when I forgot

2023-07-26 09:26 UTC, M-AminAlizadeh commented on tip-calculator-app-main/scripts/modules/btnSelection.js
> +const btnSelection = () => {
I change all of them base on clean code

2023-07-26 09:33 UTC, M-AminAlizadeh commented on tip-calculator-app-main/scripts/modules/errorHandler.js
@ahangarha I didn't get the point because the input type is number
which non-numeric characters do you mean? Please explain it specifically

2023-07-26 10:22 UTC, ahangarha commented on tip-calculator-app-main/scripts/index.js
> +errorHandler();
Good step ahead. But the better would be to break it further into two focused functions. But keep that in mind for later.

2023-07-26 10:23 UTC, ahangarha commented on .eslintrc.json
> +}
Really? They might have changed it recently.
There should be one empty line at the end of any non-empty plain text document.

2023-07-26 11:26 UTC, ahangarha approved these changes
Though there are areas for improvement, this PR can be considered as finalized.

### Optional changes:
- An empty line at the end of `.eslintrc.json` file needs to be added.
- Still, one can enter text in the form, which shouldn't be allowed.

![image](https://github.com/M-AminAlizadeh/Frontend-Mentor-projects/assets/11241315/0bd5c13b-d41e-4c66-ab72-a623f3d3eaa2)

Bests

2023-07-27 09:25 UTC, merged